# Generated by Django 5.2.6 on 2025-10-08 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('descripcion_empresa', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('is_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('usr_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_creadas', to=settings.AUTH_USER_MODEL)),
                ('usr_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('idTipoAnuncio', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('is_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('usr_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoanuncio_creadas', to=settings.AUTH_USER_MODEL)),
                ('usr_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipoanuncio_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TipoAnuncio',
                'verbose_name_plural': 'TipoAnuncios',
                'ordering': ['idTipoAnuncio'],
            },
        ),
        migrations.CreateModel(
            name='Anuncios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('is_activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('usr_crea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_creadas', to=settings.AUTH_USER_MODEL)),
                ('usr_modifica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_modificados', to=settings.AUTH_USER_MODEL)),
                ('idTipoAnuncio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.tipoanuncio')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['id'],
            },
        ),
    ]
