# Generated by Django 5.2.6 on 2025-10-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoanuncio',
            options={'ordering': ['id'], 'verbose_name': 'TipoAnuncio', 'verbose_name_plural': 'TipoAnuncios'},
        ),
        migrations.RenameField(
            model_name='tipoanuncio',
            old_name='idTipoAnuncio',
            new_name='id',
        ),
    ]
