# Generated by Django 5.2.6 on 2025-10-02 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='usr_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areas',
            name='usr_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargos',
            name='id_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.areas'),
        ),
        migrations.AddField(
            model_name='cargos',
            name='usr_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargos',
            name='usr_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_modif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='usr_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='usr_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img_modif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajesticket',
            name='usr_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajesticket',
            name='usr_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_modif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nivel',
            name='usr_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nivel',
            name='usr_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestamensajeticket',
            name='id_mensaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.mensajesticket'),
        ),
        migrations.AddField(
            model_name='respuestamensajeticket',
            name='usr_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respuestamensajeticket',
            name='usr_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_modif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.areas'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.nivel'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usr_crea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='usr_modifica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_modif', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajesticket',
            name='id_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='id_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
    ]
