# Generated by Django 5.2.6 on 2025-10-02 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='fecha_desactivacion',
        ),
        migrations.AlterField(
            model_name='nivel',
            name='usr_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveles_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
