# Generated by Django 5.2.6 on 2025-10-03 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_areas_usr_modifica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargos',
            name='usr_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imagenes',
            name='usr_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='img_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajesticket',
            name='usr_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respuestamensajeticket',
            name='usr_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='usr_modifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickes_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
